#!/bin/bash
	
#PBS -N pglmm_sim_study1
#PBS -l select=1:ncpus=16:mem=40gb
#PBS -l walltime=10:00:00

#working direction
cd /srv/scratch/z5394590/phyloglmm/R/pilot/

module purge
module load r/4.3.1
module load udunits/2.2.28
module load geos/3.9.1
module load udunits/2.2.28
module load gdal/3.5.3
module load sqlite/3.39.4
module load openssl/1.1.1s
module load proj/8.2.1
module load gsl/2.7.1


Rscript pglmm_sim_scrip1a.R