#!/bin/bash
	
#PBS -N pglmm_sim_set2a
#PBS -l select=1:ncpus=4:mem=6gb
#PBS -l walltime=11:59:00
#PBS -J 10001-20000

#working direction
cd /srv/scratch/z5394590/pglmm/set2/

module purge
module load r/4.3.1
module load udunits/2.2.28
module load geos/3.9.1
module load udunits/2.2.28
module load gdal/3.5.3
module load sqlite/3.39.4
module load openssl/1.1.1s
module load proj/8.2.1
module load gsl/2.7.1

Rscript pglmm_sim_set2a.R